---

# This file is a YAML formatted file. YAML indenting is done in spaces not
# tabs, and whitespace is significant. If you don't stick to this, it will
# fail on provision

# These are your website, and their names plugins/themes they're
# located in. See the docs for how to define these, and what all the keys
# and options are
# Remember, whitespace is significant! Tabs and spaces mean different things
app:

  setup:
    workflow: wp-cli
    wordpress: *
    env: false
    shell: false
    plugins: false
    theme: false
    settings: false
    extra: false
    
  env:
    db_name: app_db_name
    db_user: app_db_user
    db_pass: app_db_pass
    db_prefix: wp_
    app_host: example.test

  shell:
    before_install:
      - https://gist.githubusercontent.com/example.sh
    after_install:
      - https://gist.githubusercontent.com/example.sh

  plugins:
    bulks: 
      wpastra-full: *
      elementor-pro: *
    single:
      - name: plugin-name
        package: wp-cli
        ver: *
        zip: ""

  theme:
    name: astra
    package: wp-cli
    ver: *
    zip: false
    
  settings:
    # Discussion
    comment_moderation: 1
    comment_registration: 1
    default_comment_status: 0
    default_pingback_flag: 0
    default_ping_status: 0
    # General
    blogdescription: Example project
    date_format: "d/m/Y"
    time_format: "H:i"
    timezone_string: "Europe/London"
    # Media
    large_size_h: 0
    large_size_w: 0
    medium_size_h: 0
    medium_size_w: 0
    thumbnail_crop: 0
    thumbnail_size_h: 375
    thumbnail_size_w: 375
    # Miscellaneous
    convert_smilies: false
    uploads_use_yearmonth_folders: 0
    # Permalinks
    permalink_structure: "/%postname%/"
    # Privacy
    blog_public: 0
    frontpage_name: Homepage
    page_on_front: true
    # User
    admin_email: ""
    admin_password: ""
    admin_user: ""
    first_name: ""
    last_name: ""
    
  extra:
    elementor_pro_license: ""
    wp_rocket_email: ""
    wp_rocket_key: ""

  config_templates:
    env: default
    plugins_single: default
    theme: default
    settings: default
    extra: default
